In [1]:
import pandas as pd
from pandas import DataFrame
from datetime import datetime, timedelta
import dateutil.relativedelta
import re

## 計算發佈新聞前一天的收盤價

In [2]:
df = pd.read_excel('stock_data/stockdata_sentence_withdo1.xlsx')
pattern = '%Y/%m/%d'

count = 0

l1 = [] #title
l2 = [] #content
l3 = [] #key
l4 = [] #tm
l6 = [] #code
l7 = [] #start_date
l8 = [] #start_price

#找到股票代號的資料夾
for i, row in df.iterrows():
    try:
        dfs = pd.read_excel(('stock_data/stockprice/{}.xlsx').format(row['code']))
        start_price = 0
        start_date = "None"
    
    
        #往回找新聞前一天。
        if start_price == 0:
            for num in range(1, 15):
                postdate = datetime.strptime(str(row['tm']), pattern)
                fixdate_str = str(postdate + dateutil.relativedelta.relativedelta(days=-int(num))).split(' ')[0]
                fixdate = fixdate_str.replace('-','/')

                for i, rows in dfs.iterrows():
                    if rows['日期'] == fixdate:
                        start_price = rows['收盤']
                        start_date = rows['日期']
                    if not start_price == 0:
                        break
                        
        l1.extend([row['title']])
        l2.extend([row['content']])
        l3.extend([row['cat']])
        l4.extend([row['tm']])
        l6.extend([row['code']])
        l7.extend([start_date])
        l8.extend([start_price])
    
    except:
        #print(row['code'])
        start_price = 0
        start_date = 0

    count = count + 1
    if (count%1000==0):
        print(count)

result = DataFrame({'title': l1, 'content': l2, 'cat':l3, 'tm': l4, 'code': l6, 'start_date': l7, 'start_price': l8})
result

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000
159000
160000
161000
162000
163000
164000
165000
166000
167000
168000
169000
170000
171000
172000
173000
174000
175000
176000
177000
178000
179000
180000
181000
182000
183000
184000
185000
186000
187000
188000
189000
190000
191000
192000
193000
194000
195000
196000
197000
198000
199000
200000
201000
202000
203000
204000
205000
206000
207000
208000
209000
210000

,title,content,cat,tm,code,start_date,start_price
0,日盛投顧盤後－正式跌破月線 10日線為短壓,"', '4', '造紙', '1904', '正隆', '漲價', '1906', '寶隆'...",華紙,2017/03/03,1905,2017/03/02,11.35
1,日盛投顧盤後－正式跌破月線 10日線為短壓,"', '4', '造紙', '1904', '正隆', '漲價', '1906', '寶隆'...",榮成,2017/03/03,1909,2017/03/02,32.95
2,日盛投顧盤後－正式跌破月線 10日線為短壓,"', '4', '造紙', '1904', '正隆', '漲價', '1906', '寶隆'...",台紙,2017/03/03,1902,2017/03/02,12.60
3,日盛投顧盤後－正式跌破月線 10日線為短壓,"', '4', '造紙', '1904', '正隆', '漲價', '1906', '寶隆'...",正隆,2017/03/03,1904,2017/03/02,14.60
4,日盛投顧盤後－正式跌破月線 10日線為短壓,"', '4', '造紙', '1904', '正隆', '漲價', '1906', '寶隆'...",永豐餘,2017/03/03,1907,2017/03/02,11.40
...,...,...,...,...,...,...,...
205798,◆投信連續3日賣超個股,"['投信', '連續', '3日', '賣超', '個股', '1', '投信', '連續'...",新光鋼,2018/03/12,2031,2018/03/09,30.00
205799,◆投信連續3日賣超個股,"['投信', '連續', '3日', '賣超', '個股', '1', '投信', '連續'...",開發金,2018/03/12,2883,2018/03/09,10.45
205800,◆投信連續3日賣超個股,"['投信', '連續', '3日', '賣超', '個股', '1', '投信', '連續'...",大成鋼,2018/03/12,2027,2018/03/09,27.50
205801,◆投信連續3日賣超個股,"['投信', '連續', '3日', '賣超', '個股', '1', '投信', '連續'...",欣興,2018/03/12,3037,2018/03/09,19.55
205802,◆投信連續3日賣超個股,"['投信', '連續', '3日', '賣超', '個股', '1', '投信', '連續'...",揚智,2018/03/12,3041,2018/03/09,17.00

## 計算新聞發佈後第n天的開盤價

In [3]:
l1 = [] #title
l2 = [] #content
l3 = [] #key
l4 = [] #tm
l6 = [] #code
l7 = [] #start_date
l8 = [] #start_price
l9 = [] #last_date
l10 = [] #last_price
l11 = [] #labeling
pattern2 = '%Y/%m/%d'

for i, row in result.iterrows():
    try:
        dfs = pd.read_excel(('stock_data/stockprice/{}.xlsx').format(row['code']))
        last_price = 0
        last_date = "None"
    
        for i, rows in dfs.iterrows():
            pg_date_str = datetime.strptime(row['start_date'], pattern2)
            pg_date = str(pg_date_str + dateutil.relativedelta.relativedelta(days=+int(1))).split(' ')[0]
            pg_date = pg_date.replace('-','/')
            if pg_date == rows['日期']:
                last_price = rows['開盤']
                last_date = rows['日期']
            
        if last_price == 0:
            for num in range(1, 15):
                pgdate_str = datetime.strptime(row['start_date'], pattern2)
                pgdate = str(pgdate_str + dateutil.relativedelta.relativedelta(days=+int(num + 1))).split(' ')[0]
                pgdate = pgdate.replace('-','/')
                
                for i, rows in dfs.iterrows():
                    if pgdate == rows['日期']:
                        last_price = rows['開盤']
                        last_date = rows['日期']
                    if not last_price == 0:
                        break
                    
        if ( last_price - row['start_price'] ) > 0:
            labeling = '1'
        elif ( last_price - row['start_price'] ) < 0:
            labeling = '0'
        else:
            labeling = ''
 
        l1.extend([row['title']])
        l2.extend([row['content']])
        l3.extend([row['cat']])
        l4.extend([row['tm']])
        l6.extend([row['code']])
        l7.extend([row['start_date']])
        l8.extend([row['start_price']])                
        l9.extend([last_date])
        l10.extend([last_price])
        l11.extend([labeling])

    except:
        start_price = 0
        start_date = 0
        
result2 = DataFrame({'title': l1, 'content': l2, 'cat':l3, 'tm': l4, 'code': l6, 'start_date': l7, 'start_price': l8, 'last_date': l9, 'last_price': l10, 'labeling': l11})
result2.to_excel('stock_data/stockdata_finish_new1.xlsx')